packages:
  - docs
  - packages/**
  - playground/**
catalog:
  '@antfu/eslint-config': ^3.12.1
  '@antfu/ni': ^0.23.2
  '@faker-js/faker': ^9.3.0
  '@headlessui/vue': ^1.7.23
  '@iconify-json/heroicons': ^1.2.2
  '@iconify-json/lucide': ^1.2.21
  '@iconify-json/radix-icons': ^1.2.2
  '@iconify-json/tabler': ^1.2.13
  '@iconify/json': ^2.2.292
  '@nuxt/devtools': ^1.7.0
  '@nuxt/kit': ^3.15.1
  '@nuxt/module-builder': ^0.8.4
  '@nuxt/schema': ^3.15.1
  '@nuxtjs/color-mode': ^3.5.2
  '@tanstack/vue-table': ^8.20.5
  '@types/chroma-js': ^2.4.5
  '@types/fs-extra': ^11.0.4
  '@types/markdown-it': ^14.1.2
  '@types/node': ^22.10.5
  '@una-ui/content': ^0.0.40
  '@unocss/core': ^0.64.1
  '@unocss/eslint-config': ^0.64.1
  '@unocss/nuxt': ^0.64.1
  '@unocss/preset-attributify': ^0.64.1
  '@unocss/preset-icons': ^0.64.1
  '@unocss/preset-mini': ^0.64.1
  '@vee-validate/nuxt': ^4.15.0
  '@vee-validate/zod': ^4.15.0
  '@vercel/analytics': ^1.4.1
  '@vueuse/core': ^12.3.0
  '@vueuse/integrations': ^12.3.0
  '@vueuse/nuxt': ^12.3.0
  bumpp: ^9.9.2
  chroma-js: ^3.1.2
  clsx: ^2.1.1
  conventional-changelog-cli: ^5.0.0
  eslint: ^9.17.0
  eslint-plugin-format: ^0.1.3
  esno: ^4.8.0
  fast-glob: ^3.3.3
  fs-extra: ^11.2.0
  ignore-dependency-scripts: ^1.0.1
  lint-staged: ^15.3.0
  nuxt: ^3.15.1
  ohash: ^1.1.4
  pathe: ^1.1.2
  radix-vue: ^1.9.12
  rimraf: ^6.0.1
  sass: ^1.83.1
  simple-git: ^3.27.0
  simple-git-hooks: ^2.11.1
  tailwind-merge: ^2.6.0
  typescript: 5.6.3
  unbuild: ^2.0.0
  unocss: ^0.64.1
  unocss-preset-animations: ^1.1.0
  vitest: ^2.1.8
  vue-tsc: ^2.2.0
  zod: ^3.24.1
