packages:
  - docs
  - packages/**
  - playground/**
catalog:
  '@antfu/eslint-config': ^3.10.0
  '@antfu/ni': ^0.23.1
  '@faker-js/faker': ^9.2.0
  '@headlessui/vue': ^1.7.23
  '@iconify-json/heroicons': ^1.2.1
  '@iconify-json/lucide': ^1.2.16
  '@iconify-json/radix-icons': ^1.2.1
  '@iconify-json/tabler': ^1.2.8
  '@iconify/json': ^2.2.276
  '@nuxt/devtools': ^1.6.1
  '@nuxt/kit': ^3.14.1592
  '@nuxt/module-builder': ^0.8.4
  '@nuxt/schema': ^3.14.1592
  '@nuxtjs/color-mode': ^3.5.2
  '@tanstack/vue-table': ^8.20.5
  '@types/chroma-js': ^2.4.4
  '@types/fs-extra': ^11.0.4
  '@types/markdown-it': ^14.1.2
  '@types/node': ^22.10.0
  '@una-ui/content': ^0.0.40
  '@unocss/core': ^0.64.1
  '@unocss/eslint-config': ^0.64.1
  '@unocss/nuxt': ^0.64.1
  '@unocss/preset-attributify': ^0.64.1
  '@unocss/preset-icons': ^0.64.1
  '@unocss/preset-mini': ^0.64.1
  '@vercel/analytics': ^1.4.1
  '@vueuse/core': ^12.0.0
  '@vueuse/integrations': ^12.0.0
  '@vueuse/nuxt': ^12.0.0
  bumpp: ^9.8.1
  chroma-js: ^3.1.2
  clsx: ^2.1.1
  conventional-changelog-cli: ^5.0.0
  eslint: ^9.15.0
  esno: ^4.8.0
  fast-glob: ^3.3.2
  fs-extra: ^11.2.0
  ignore-dependency-scripts: ^1.0.1
  lint-staged: ^15.2.10
  nuxt: ^3.14.1592
  ohash: ^1.1.4
  pathe: ^1.1.2
  radix-vue: ^1.9.10
  rimraf: ^6.0.1
  sass: ^1.81.0
  simple-git: ^3.27.0
  simple-git-hooks: ^2.11.1
  tailwind-merge: ^2.5.5
  typescript: 5.6.3
  unbuild: ^2.0.0
  unocss: ^0.64.1
  unocss-preset-animations: ^1.1.0
  vitest: ^2.1.6
  vue-tsc: ^2.1.10
